# JVM 参数：给 Gradle/Xmx 留出足够堆内存
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
# AGP 对 compileSdk 37 小版本平台（Android 17）的兼容性抑制
android.suppressUnsupportedCompileSdk=37,37.0

# Kotlin 代码风格
kotlin.code.style=official
